# Generated by Django 5.2.1 on 2025-08-07 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_administradores', '0001_initial'),
        ('app_areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('eve_id', models.AutoField(primary_key=True, serialize=False)),
                ('eve_nombre', models.CharField(max_length=100)),
                ('eve_descripcion', models.CharField(max_length=400)),
                ('eve_ciudad', models.CharField(max_length=45)),
                ('eve_lugar', models.CharField(max_length=45)),
                ('eve_fecha_inicio', models.DateField()),
                ('eve_fecha_fin', models.DateField()),
                ('eve_estado', models.CharField(max_length=45)),
                ('eve_imagen', models.ImageField(blank=True, null=True, upload_to='eventos/imagenes/')),
                ('eve_capacidad', models.IntegerField()),
                ('eve_tienecosto', models.CharField(max_length=2)),
                ('eve_programacion', models.FileField(blank=True, null=True, upload_to='eventos/programaciones/')),
                ('eve_memorias', models.FileField(blank=True, null=True, upload_to='eventos/memorias/')),
                ('eve_administrador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='app_administradores.administradorevento')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('asistencia', 'Asistencia'), ('participacion', 'Participación'), ('evaluador', 'Evaluador')], max_length=20)),
                ('plantilla', models.CharField(choices=[('elegante', 'Elegante'), ('moderno', 'Moderno'), ('clasico', 'Clásico')], default='elegante', max_length=20)),
                ('titulo', models.CharField(default='Certificado', max_length=200)),
                ('cuerpo', models.TextField(help_text='Puedes usar {nombre}, {evento}, {fecha}, etc.')),
                ('firma', models.ImageField(blank=True, null=True, upload_to='certificados/firmas/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certificados/logos/')),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_certificado', to='app_eventos.evento')),
            ],
            options={
                'unique_together': {('evento', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='EventoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_areas.categoria')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento')),
            ],
            options={
                'unique_together': {('evento', 'categoria')},
            },
        ),
    ]
