# Generated by Django 5.2.1 on 2025-07-23 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_administradores', '0001_initial'),
        ('app_areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('eve_id', models.AutoField(primary_key=True, serialize=False)),
                ('eve_nombre', models.CharField(max_length=100)),
                ('eve_descripcion', models.CharField(max_length=400)),
                ('eve_ciudad', models.CharField(max_length=45)),
                ('eve_lugar', models.CharField(max_length=45)),
                ('eve_fecha_inicio', models.DateField()),
                ('eve_fecha_fin', models.DateField()),
                ('eve_estado', models.CharField(max_length=45)),
                ('eve_imagen', models.ImageField(blank=True, null=True, upload_to='eventos/imagenes/')),
                ('eve_capacidad', models.IntegerField()),
                ('eve_tienecosto', models.CharField(max_length=2)),
                ('eve_programacion', models.FileField(blank=True, null=True, upload_to='eventos/programaciones/')),
                ('eve_memorias', models.FileField(blank=True, null=True, upload_to='eventos/memorias/')),
                ('eve_administrador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='app_administradores.administradorevento')),
            ],
        ),
        migrations.CreateModel(
            name='EventoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_areas.categoria')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento')),
            ],
            options={
                'unique_together': {('evento', 'categoria')},
            },
        ),
    ]
