# Generated by Django 5.2.1 on 2025-07-24 05:40

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rol', models.CharField(choices=[('participante', 'Participante'), ('asistente', 'Asistente'), ('evaluador', 'Evaluador')], max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('documento', models.CharField(max_length=20)),
                ('evento_id', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='inscripciones_pendientes/')),
                ('datos_extra', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
