# Generated by Django 5.2.4 on 2025-08-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='eve_lugar',
            field=models.CharField(max_length=200),
        ),
    ]
