# Generated by Django 5.2.1 on 2025-07-26 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0002_inscripcionpendiente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InscripcionPendiente',
        ),
    ]
