# Generated by Django 5.2.4 on 2025-09-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0002_alter_evento_eve_lugar'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='inscripciones_habilitadas',
            field=models.BooleanField(default=False),
        ),
    ]
