# Generated by Django 5.2.4 on 2025-09-15 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0003_evento_inscripciones_habilitadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='inscripciones_habilitadas',
        ),
    ]
