# Generated by Django 5.2.1 on 2025-07-30 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0003_delete_inscripcionpendiente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('asistencia', 'Asistencia'), ('participacion', 'Participación'), ('evaluador', 'Evaluador')], max_length=20)),
                ('titulo', models.CharField(default='Certificado', max_length=200)),
                ('cuerpo', models.TextField(help_text='Puedes usar {{ nombre }}, {{ evento }}, {{ fecha }}, etc.')),
                ('firma', models.ImageField(blank=True, null=True, upload_to='certificados/firmas/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certificados/logos/')),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_certificado', to='app_eventos.evento')),
            ],
            options={
                'unique_together': {('evento', 'tipo')},
            },
        ),
    ]
