# Generated by Django 5.2.1 on 2025-07-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0005_configuracioncertificado_plantilla_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncertificado',
            name='plantilla',
            field=models.CharField(choices=[('elegante', 'Elegante'), ('moderno', 'Moderno'), ('clasico', 'Clásico')], default='moderno', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='cuerpo',
            field=models.TextField(help_text='Puedes usar {nombre}, {evento}, {fecha}, etc.'),
        ),
    ]
