# Generated by Django 5.2.1 on 2025-07-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0006_configuracioncertificado_plantilla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioncertificado',
            name='plantilla_html',
        ),
    ]
