# Generated by Django 5.2.1 on 2025-07-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0007_remove_configuracioncertificado_plantilla_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncertificado',
            name='plantilla_html',
            field=models.TextField(blank=True, help_text='HTML base de la plantilla seleccionada', null=True),
        ),
    ]
