# Generated by Django 5.2.1 on 2025-07-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0008_configuracioncertificado_plantilla_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioncertificado',
            name='plantilla',
        ),
    ]
