# Generated by Django 5.2.1 on 2025-07-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0009_remove_configuracioncertificado_plantilla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracioncertificado',
            name='plantilla_html',
        ),
        migrations.AddField(
            model_name='configuracioncertificado',
            name='plantilla',
            field=models.CharField(choices=[('elegante', 'Elegante'), ('moderno', 'Moderno'), ('clasico', 'Clásico')], default='elegante', max_length=20),
        ),
    ]
