# Generated by Django 5.2.1 on 2025-07-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0010_remove_configuracioncertificado_plantilla_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='tipo',
            field=models.CharField(choices=[('asistencia', 'Asistencia'), ('participacion', 'Participación'), ('evaluador', 'Evaluador'), ('premiacion', 'Premiación')], max_length=20),
        ),
    ]
