# Generated by Django 5.2.1 on 2025-07-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0011_alter_configuracioncertificado_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncertificado',
            name='tipo',
            field=models.CharField(choices=[('asistencia', 'Asistencia'), ('participacion', 'Participación'), ('evaluador', 'Evaluador')], max_length=20),
        ),
    ]
