# Generated by Django 5.2.1 on 2025-08-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AsistenteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asi_eve_fecha_hora', models.DateTimeField()),
                ('asi_eve_estado', models.CharField(max_length=45)),
                ('asi_eve_soporte', models.FileField(blank=True, null=True, upload_to='asistentes/soportes/')),
                ('asi_eve_qr', models.ImageField(blank=True, null=True, upload_to='asistentes/qr/')),
                ('confirmado', models.BooleanField(default=False)),
            ],
        ),
    ]
