# Generated by Django 5.2.1 on 2025-08-07 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_asistentes', '0001_initial'),
        ('app_eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asistente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistenteevento',
            name='asistente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_asistentes.asistente'),
        ),
        migrations.AddField(
            model_name='asistenteevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento'),
        ),
        migrations.AlterUniqueTogether(
            name='asistenteevento',
            unique_together={('asistente', 'evento')},
        ),
    ]
