# Generated by Django 5.2.1 on 2025-08-07 23:08

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministradorEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CodigoInvitacionAdminEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=uuid.uuid4, editable=False, max_length=32, unique=True)),
                ('email_destino', models.EmailField(max_length=254)),
                ('limite_eventos', models.PositiveIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_expiracion', models.DateTimeField()),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('usado', 'Usado'), ('expirado', 'Expirado'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], default='activo', max_length=12)),
                ('tiempo_limite_creacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
