# Generated by Django 5.2.1 on 2025-08-13 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_administradores', '0001_initial'),
        ('app_eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='administradorevento',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codigoinvitacionadminevento',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codigoinvitacionevento',
            name='administrador_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_creados', to='app_administradores.administradorevento'),
        ),
        migrations.AddField(
            model_name='codigoinvitacionevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_invitacion', to='app_eventos.evento'),
        ),
    ]
