# Generated by Django 5.2.1 on 2025-07-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_administradores', '0003_codigoinvitacionadminevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoinvitacionadminevento',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('usado', 'Usado'), ('expirado', 'Expirado'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=12),
        ),
    ]
