# Generated by Django 5.2.1 on 2025-06-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipanteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_eve_fecha_hora', models.DateTimeField()),
                ('par_eve_documentos', models.FileField(blank=True, null=True, upload_to='participantes/documentos/')),
                ('par_eve_estado', models.CharField(max_length=45)),
                ('par_eve_qr', models.ImageField(blank=True, null=True, upload_to='participantes/qr/')),
                ('par_eve_clave', models.CharField(max_length=45)),
                ('par_eve_valor', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
