# Generated by Django 5.2.1 on 2025-08-13 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_eventos', '0001_initial'),
        ('app_participantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participanteevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento'),
        ),
        migrations.AddField(
            model_name='participanteevento',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_participantes.participante'),
        ),
        migrations.AlterUniqueTogether(
            name='participanteevento',
            unique_together={('participante', 'evento')},
        ),
    ]
