# Generated by Django 5.2.1 on 2025-08-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_participantes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participanteevento',
            name='par_eve_valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
