# Generated by Django 5.2.4 on 2025-09-13 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0002_alter_evento_eve_lugar'),
        ('app_participantes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanteevento',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código de proyecto grupal', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='proyectos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='app_eventos.evento')),
            ],
        ),
        migrations.AddField(
            model_name='participanteevento',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes', to='app_participantes.proyecto'),
        ),
    ]
