# Generated by Django 5.2.1 on 2025-07-26 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_participantes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participanteevento',
            name='par_eve_clave',
        ),
    ]
