# Generated by Django 5.2.4 on 2025-09-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_participantes', '0003_participanteevento_codigo_proyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='pro_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
