# Generated by Django 5.2.1 on 2025-07-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_participantes', '0003_remove_participanteevento_par_eve_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='participanteevento',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
