# Generated by Django 5.2.1 on 2025-06-17 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_eventos', '0001_initial'),
        ('app_participantes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('cri_id', models.AutoField(primary_key=True, serialize=False)),
                ('cri_descripcion', models.CharField(max_length=100)),
                ('cri_peso', models.FloatField()),
                ('cri_evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='app_eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_valor', models.IntegerField()),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_participantes.participante')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_evaluadores.criterio')),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_evaluadores.evaluador')),
            ],
            options={
                'unique_together': {('evaluador', 'criterio', 'participante')},
            },
        ),
        migrations.CreateModel(
            name='EvaluadorEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eva_eve_fecha_hora', models.DateTimeField()),
                ('eva_eve_estado', models.CharField(max_length=45)),
                ('eva_eve_qr', models.ImageField(blank=True, null=True, upload_to='evaluadores/qr/')),
                ('eva_eve_clave', models.CharField(blank=True, max_length=45, null=True)),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento')),
            ],
            options={
                'unique_together': {('evaluador', 'evento')},
            },
        ),
    ]
