# Generated by Django 5.2.1 on 2025-08-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_valor', models.IntegerField()),
                ('cal_observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('cri_id', models.AutoField(primary_key=True, serialize=False)),
                ('cri_descripcion', models.CharField(max_length=100)),
                ('cri_peso', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluadorEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eva_eve_documentos', models.FileField(blank=True, null=True, upload_to='evaluadores/documentos/')),
                ('eva_eve_fecha_hora', models.DateTimeField()),
                ('eva_eve_estado', models.CharField(max_length=45)),
                ('eva_eve_qr', models.ImageField(blank=True, null=True, upload_to='evaluadores/qr/')),
                ('confirmado', models.BooleanField(default=False)),
            ],
        ),
    ]
