# Generated by Django 5.2.1 on 2025-06-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evaluadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluadorevento',
            name='eva_eve_documentos',
            field=models.FileField(blank=True, null=True, upload_to='evaluadores/documentos/'),
        ),
    ]
