# Generated by Django 5.2.1 on 2025-07-23 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_evaluadores', '0002_initial'),
        ('app_eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_evaluadores.evaluador'),
        ),
        migrations.AddField(
            model_name='evaluadorevento',
            name='evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluadorevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eventos.evento'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('evaluador', 'criterio', 'participante')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluadorevento',
            unique_together={('evaluador', 'evento')},
        ),
    ]
