# Generated by Django 5.2.4 on 2025-09-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evaluadores', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluadorevento',
            name='puede_gestionar_rubrica',
            field=models.BooleanField(default=False),
        ),
    ]
