# Generated by Django 5.2.1 on 2025-07-26 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evaluadores', '0004_remove_evaluadorevento_eva_eve_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluadorevento',
            name='evaluador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_evaluadores.evaluador'),
        ),
    ]
