# Generated by Django 5.2.1 on 2025-07-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_evaluadores', '0005_alter_evaluadorevento_evaluador'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluadorevento',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
